### ISSUE TITLE
Background apps and processes 

### ISSUE THREAD

**Issue by Sportlife24** [visnkmr/visnkmr#3] opened 2023-08-03 15:01 UTC
Please update background and processes app.
Thank you

**Comment by visnkmr** [comment] 2023-08-03 21:24
Hey,
You may have experienced crashes in Background Apps and Process List if you are using older versions of the app. To fix this, please update the app from your device’s appstore. The appstores may not auto-update the app, so you need to check manually.
Latest version on:

Fire OS appstore is 1.3A12I,
Google play version is 1.3G10I.

**Comment by Darknessangel27** [comment] 2023-08-04 05:32
It's seem my background apps & process list was Forgotten to update on my fire stick and my device time is correct.

**Comment by visnkmr** [comment] 2023-08-04 20:24
> I have not experienced any crashes but when I opened the app today on my Insignia Fire TV, OS 7.6.4.6 (PS7646/3550), Home 6460037.1, and was greeted with an new intro screen that read:
> 
> > The version of the app you have installed is 1.3A10i
> > Today's date as per your device is 04 August 2023
> > Update available.
> > [Video] How to enable overlay permission for android app via adb
> 
> I do not use Time Net Speed Monitor on my Fire TV so I do not believe this video will solve my issue. Please correct me if I am wrong.
> 
> I clicked the "UPDATE APP" button then the "Open app on Appstore" button, but it just crashed and took me to the "Find" screen.
> 
> So I then go to the video above, at the source, to read the comments, where I find your [Telegram Channel](https://t.me/s/vishnunkmr).
> 
> I view the preview of the channel which leads me here, where you say to manually upgrade.
> 
> From the Appstore website, I can see that [the current version of Background Apps and Processes List on the Appstore is 1.3A12i](https://www.amazon.com/Background-Apps-Process-List-Legacy/dp/B07JF3CDVZ#:~:text=Version%3A-,1.3A12i,-Developed%20By%3A) but I am unable to do a manual update. The Appstore on my Fire TV only gives the option to open the app and not to update it.
> 
> * Is there a way to sideload 1.3A12i on my Fire TV?
> * Or is there a better solution for my case?
> 
> Thank you for the wonderful app and keep up the good work!

There seems to be some issue with amazon appstore such that it installs a version that is older than the active version, Upon further checking this issue is present on other apps on the appstore as well. Since this is a global issue I estimate the issue will be resolved fairly quickly. 

APK for the latest release available @ https://github.com/visnkmr/backgroundappslist/releases

**Comment by visnkmr** [comment] 2023-11-02 05:47
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.

**Closed by visnkmr** 2023-11-02 05:47 UTC

**Comment by JLC251** [comment] 2024-01-24 22:07
I am currently having this SAME problem with your app called Background Apps and Processes List. 
I currently have 1.3A12i, but just as your other user said about your other app, it is not taking me to the Amazon app store to update it. 
What do I do?

**Comment by visnkmr** [comment] 2024-01-25 06:33
> I am currently having this SAME problem with your app called Background Apps and Processes List. I currently have 1.3A12i, but just as your other user said about your other app, it is not taking me to the Amazon app store to update it. What do I do?

Could you please refer to https://github.com/visnkmr/visnkmr/issues/24

**Comment by aerogurl** [comment] 2024-03-06 06:50
I have a question. I recently downloaded the app and when I closed all the apps and processes that were open in the background it, seemingly I loved it and it did exactly what it was supposed to. However I'm not sure if maybe Accessibility updated or I'm not sure about all my app permissions were removed. All my folders I had with apps and widgets did not show the icons anymore they were blank and it looked like the app didn't exist anymore. The apps are still there but I've had to totally redo my widgets. Then I went to my appmgr to clean my cache, and realize that all permissions across the board on all my apps were removed like restricted. I had to go into more options in the individual apps and reset their restrictive settings. Is this an issue that You already knew of or do you think it is your app or could be your app that's done that? I don't think I've installed anything else or gave anything else permission over my Android like that. Just don't want to keep using it and make that mistake again and wipe things out, because I do like it. Thanks for any hope you can provide.

**Comment by visnkmr** [comment] 2024-03-06 07:23
Background apps and process list does not use any permission. It does not need or use Accessibility or system permission.  This happened most probably because of the either of the two
- system update that may have introduced this as a feature much like the freezing feature that was available in samsung and other oem devices, something similar is also coming in next version of android from my understanding.
- appmgr app you mentioned that cleans cache. It may have had a background update that removes permissions of unused or non background running apps. that is the most probable scenario. Since cleaning cache requires system permission that does not exist in android anymore except for oem and rooted apps from my understanding.

**Comment by Foden7** [comment] 2024-06-08 22:44
Have an issue with my son's Firestick, not sure hwat version of the app he is running - but must be old. On bootup the screen breifly flashes a screen similar to

Today's date as per your device is.....
It seems you are using a obsolete(very old) version of the app.
blah blah
blah blah

OK                       Update App

Problem is this is overlaid with another message

You must be logged in to run this application

But I cannot login or get to the update app button!

I don;t want to have to reset his firestick but have no idea how to stop this loop

Any assitance would be appreciated

**Comment by visnkmr** [comment] 2024-06-09 19:46
Hey,

I regret to inform you that our recent app updates on Google Play have encountered rejection due to policy issues concerning app icon sizes for Android TV. The specific problem has been outlined [here](https://support.google.com/googleplay/android-developer/thread/270001289/android-tv-app-rejected-with-reason-no-full-size-app-banner-and-or-icon?hl=en).

Should you have any connections within Google's Play Store teams, we kindly request your assistance. Please reach out to us on Github if you can offer any insights or assistance in resolving this matter. In the interim, we will continue to submit updates periodically to Google play for review.

For uninterrupted access to the latest versions of our apps, they are readily available on our [appstore](https://visnkmr.github.io/appstore).

I appreciate your patience and understanding as we endeavor to improve your app experience.

Thank you.

**Comment by Foden7** [comment] 2024-06-09 19:56
Hi, Yes I had seen that earlier. Is there sany way to stop the app loading, as it is stuck in the above loop. It nevers gets to the main Amazon memu

**Comment by visnkmr** [comment] 2024-06-09 20:08
If the issue is being faced on a firestick the update should already be available on its appstore. Even then if you face the same issue just uncheck the "start app on boot" option in preference.

**Comment by Foden7** [comment] 2024-06-09 22:30
That's the problem, we can't. That screen is behind the You need to login to use this app  screen

**Comment by Foden7** [comment] 2024-06-10 03:53
![Screenshot_20240609-214935](https://github.com/visnkmr/visnkmr/assets/35184114/9838b57a-9ca4-4812-b070-477c8f90c039)
![Screenshot_20240609-214922](https://github.com/visnkmr/visnkmr/assets/35184114/2be303dc-8073-4cd5-8f24-5f8915682f0d)
![Screenshot_20240609-214933](https://github.com/visnkmr/visnkmr/assets/35184114/f184f0e2-1136-4563-82a4-208b5309bafd)

**Comment by visnkmr** [comment] 2024-06-10 08:59
Since its a firestick the only way would be to uninstall the app and wait for a few days and reinstall, since this is an issue with amazon appstore that comes preinstalled on firetv there's not much that can be done. The app requiring an update and the login screen should in no way be related. The same issue had come up for me a while back and it disappeared after a few days. I don't know of the exact cause for this issue as it happens on my device at random occassions.

**Comment by Foden7** [comment] 2024-06-10 14:06
Thanks
